from .linux_props import \
    NMCLI_TARGET_PROPS, \
    RSYSLOG_CONF_FILE, \
    RSYSLOG_CONF_D, \
    SSHD_CONF_FILE, \
    SSHD_CONF_D, \
    LOGROTATE_CONF_FILE, \
    LOGROTATE_CONF_D, \
    CRON_CONF_D, \
    USER_CRON_CONF_D, \
    CHRONY_CONF_FILE, \
    DNF_CONF_FILE, \
    DNF_REPO_D, \
    DNF_REPO_EXCLUSION, \
    SUDOERS_CONF, \
    SUDOERS_CONF_D, \
    AUTHSELECT_PATH, \
    AUTHSELECT_TARGET

from .linux_oss_props import \
    CONF_HTTPD, \
    CONF_HTTPD_D, \
    CONF_HTTPD_MODULES, \
    CONF_HTTPD_ROOT, \
    CONF_POSTFIX_MAIN, \
    CONF_POSTFIX_MASTER, \
    CONF_POSTFIX_ALIASES, \
    CONF_POSTFIX_ACCESS, \
    CONF_POSTFIX_TRANSPORT, \
    CONF_POSTFIX_VIRTUAL, \
    CONF_PG_HBA_CONF, \
    CONF_POSTGRESQL_CONF, \
    CONF_MYSQL, \
    CONF_MYSQL_D, \
    CONF_SQUID, \
    CONF_NAMED, \
    ROOTDIR_NAMED_CHROOT, \
    CONF_NFS_IDMAP, \
    CONF_NFS_EXPORT, \
    CONF_SMB, \
    CONF_SSSD

from .zabbix_props import \
    CONF_ZABBIX_SERVER_CONF, \
    CONF_ZABBIX_SERVER_CONF_D, \
    CONF_ZABBIX_AGENT_CONF, \
    CONF_ZABBIX_AGENT_CONF_D, \
    CONF_ZABBIX_WEB_CONF

__all__ = [
    'NMCLI_TARGET_PROPS',
    'RSYSLOG_CONF_FILE',
    'RSYSLOG_CONF_D',
    'SSHD_CONF_FILE',
    'SSHD_CONF_D',
    'LOGROTATE_CONF_FILE',
    'LOGROTATE_CONF_D',
    'CRON_CONF_D',
    'USER_CRON_CONF_D',
    'CHRONY_CONF_FILE',
    'DNF_CONF_FILE',
    'DNF_REPO_D',
    'DNF_REPO_EXCLUSION',
    'SUDOERS_CONF',
    'SUDOERS_CONF_D',
    'CONF_HTTPD',
    'CONF_HTTPD_D',
    'CONF_HTTPD_MODULES',
    'CONF_HTTPD_ROOT',
    'CONF_POSTFIX_MAIN',
    'CONF_POSTFIX_MASTER',
    'CONF_POSTFIX_ALIASES',
    'CONF_POSTFIX_ACCESS',
    'CONF_POSTFIX_TRANSPORT',
    'CONF_POSTFIX_VIRTUAL',
    'CONF_PG_HBA_CONF',
    'CONF_POSTGRESQL_CONF',
    'CONF_MYSQL',
    'CONF_MYSQL_D',
    'CONF_SQUID',
    'CONF_NAMED',
    'ROOTDIR_NAMED_CHROOT',
    'CONF_NFS_IDMAP',
    'CONF_NFS_EXPORT',
    'CONF_SMB',
    'AUTHSELECT_PATH',
    'AUTHSELECT_TARGET',
    'CONF_SSSD',
    'CONF_ZABBIX_SERVER_CONF',
    'CONF_ZABBIX_SERVER_CONF_D',
    'CONF_ZABBIX_AGENT_CONF',
    'CONF_ZABBIX_AGENT_CONF_D',
    'CONF_ZABBIX_WEB_CONF'
]
